probe_calibration_test: calibration_surface.cpp pressures_to_airdata.cpp probe_calibration_test_main.cpp
	g++ $^ -o $@

calibration_surface_test: calibration_surface.cpp calibration_surface_test_main.cpp
	g++ $^ -o $@
